import os.path

HOME = os.path.expanduser('~')
EZPROXY = 'YOUR EZPROXY PREFIX'
MAX_WORKERS = 20
MISCONFIGURED_DATABASES = []  # not a constant, kind of the opposite, so sue me
LIBGUIDES_API_URL = 'API ENDPOINT FOR LIBGUIDES DATABASE LIST
ERROR_TEXT = 'TEXT UNIQUE TO YOUR EZPROXY INSTANCE'
KB_KEY = 'A WSKEY FOR OCLC KNOWLEDGE BASE API'
SCREENSHOT_LOCATION = 'screenshots'
KB_COLLECTION = 'THE KNOWLEDGE BASE COLLECTION TO CHECK'
